# Generated by Django 5.0.6 on 2024-06-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="conModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cement", models.FloatField()),
                ("slag", models.FloatField()),
                ("flyash", models.FloatField()),
                ("water", models.FloatField()),
                ("superplasticizer", models.FloatField()),
                ("coarseaggreate", models.FloatField()),
                ("fineaggregate", models.FloatField()),
                ("age", models.FloatField()),
            ],
        ),
    ]
